[package]
name = "ghtui-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ghtui-theme.workspace = true
ghtui-api.workspace = true
ghtui-diff.workspace = true
ghtui-git.workspace = true
ratatui.workspace = true
ratatui-textarea.workspace = true
unicode-segmentation = "1"
unicode-width = "0.2"
pulldown-cmark.workspace = true


[dev-dependencies]
proptest.workspace = true
flate2.workspace = true
insta.workspace = true
serde_json.workspace = true

[lints]
workspace = true
